spring:
  datasource:
    url: jdbc:postgresql://localhost/gowpet-pos
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false
