name: Run tests

on:
  workflow_call:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Prepare maven
        uses: ./.github/actions/prepare-maven

      - name: Run tests
        run: mvn -B verify --file pom.xml
        shell: bash
