name: Test PR

on: pull_request

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Java 18
        uses: actions/setup-java@v1
        with:
          java-version: 18
      - name: Set up cache
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{runner.os}}-m2
      - name: Run tests
        run: mvn -B test --file pom.xml
