name: Push to feature branch

on:
  push:
    branches:
      - feature/*

jobs:
  run-tests:
    uses: './.github/workflows/reusable-test.yaml'
  
  build-and-publish-image:
    permissions: write-all
    needs: [run-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      # Start of the Java section
      
      - name: Prepare maven
        uses: ./.github/actions/prepare-maven

      - name: Create jar
        run: mvn install -DskipTests
        shell: bash

      # Start of the Docker section

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build image and push to GHCR
        uses: docker/build-push-action@v2
        with:
          tags: |
            ghcr.io/jonfelixrico/gowpet-pos-backend:beta
          context: .
          push: true